
export const deadlinesData = [
  { id: 1, title: 'Senior Geologist Application Deadline', type: 'Job Posting', category: 'jobs', date: '2025-01-28', daysLeft: 3, priority: 'urgent', status: 'active', description: 'Job posting for Senior Geologist position closing soon. 45 applications received so far.', assignedTo: 'Self', relatedModule: 'Jobs Management', details: ['45 applications received', 'Shortlisting in progress', 'Interview panel confirmed'], createdAt: 'Jan 05, 2025', updatedAt: 'Jan 20, 2025' },
  { id: 2, title: 'Q4 Financial Report Upload', type: 'Resource Upload', category: 'resources', date: '2025-01-30', daysLeft: 5, priority: 'high', status: 'active', description: 'Upload Q4 2024 financial statements to the Resources Center for stakeholder access.', assignedTo: 'Self', relatedModule: 'Resources Center', details: ['Financial data compiled', 'Awaiting final approval', 'PDF conversion pending'], createdAt: 'Jan 10, 2025', updatedAt: 'Jan 22, 2025' },
  { id: 3, title: 'Vedanta Partnership Inquiry Response', type: 'Inquiry Response', category: 'inquiries', date: '2025-02-01', daysLeft: 7, priority: 'high', status: 'active', description: 'Draft and send detailed response to Vedanta Resources regarding their partnership proposal.', assignedTo: 'Self', relatedModule: 'Inquiries', details: ['Review partnership proposal', 'Get management input', 'Draft formal response'], createdAt: 'Jan 07, 2025', updatedAt: 'Jan 19, 2025' },
  { id: 4, title: 'Electrical Engineer Position Closing', type: 'Job Posting', category: 'jobs', date: '2025-02-05', daysLeft: 11, priority: 'medium', status: 'active', description: 'Recruitment deadline for Electrical Engineer to support plant maintenance operations.', assignedTo: 'Self', relatedModule: 'Jobs Management', details: ['28 applications received', 'Technical test prepared', 'Salary range approved'], createdAt: 'Jan 08, 2025', updatedAt: 'Jan 19, 2025' },
  { id: 5, title: 'Download Requests Review Deadline', type: 'Resource Review', category: 'resources', date: '2025-02-08', daysLeft: 14, priority: 'medium', status: 'active', description: 'Process and approve or reject all pending download requests for restricted documents.', assignedTo: 'Self', relatedModule: 'Resources Center', details: ['7 pending requests', 'Verify requester credentials', 'Send approval notifications'], createdAt: 'Jan 12, 2025', updatedAt: 'Jan 20, 2025' },
  { id: 6, title: 'Community Complaint Response', type: 'Inquiry Response', category: 'inquiries', date: '2025-01-25', daysLeft: 0, priority: 'urgent', status: 'active', description: 'Respond to community complaint regarding dust emissions from the processing plant.', assignedTo: 'Self', relatedModule: 'Inquiries', details: ['Coordinate with HSE team', 'Prepare mitigation report', 'Draft formal response'], createdAt: 'Jan 06, 2025', updatedAt: 'Jan 16, 2025' },
  { id: 7, title: 'Maintenance Technician Hiring', type: 'Job Posting', category: 'jobs', date: '2025-02-15', daysLeft: 21, priority: 'low', status: 'active', description: 'Hiring deadline for maintenance technicians for plant equipment servicing.', assignedTo: 'Self', relatedModule: 'Jobs Management', details: ['15 applications received', 'Skills assessment planned', 'Training program ready'], createdAt: 'Jan 12, 2025', updatedAt: 'Jan 21, 2025' },
  { id: 8, title: 'Policy Documents Update', type: 'Resource Upload', category: 'resources', date: '2025-02-18', daysLeft: 24, priority: 'medium', status: 'active', description: 'Replace outdated policy documents with the latest approved versions from management.', assignedTo: 'Self', relatedModule: 'Resources Center', details: ['HSE Policy v3.2 update', 'Anti-Corruption Policy new', 'Employee Handbook 2025'], createdAt: 'Jan 11, 2025', updatedAt: 'Jan 17, 2025' },
  { id: 9, title: 'Media Inquiry - Expansion Plans', type: 'Inquiry Response', category: 'inquiries', date: '2025-02-10', daysLeft: 16, priority: 'medium', status: 'active', description: 'Prepare official response to Zambia Daily Mail inquiry about company expansion plans.', assignedTo: 'Self', relatedModule: 'Inquiries', details: ['Get approved talking points', 'Draft press-ready response', 'Management review'], createdAt: 'Jan 10, 2025', updatedAt: 'Jan 18, 2025' },
  { id: 10, title: 'ISO 14001 Certification Upload', type: 'Resource Upload', category: 'resources', date: '2025-01-15', daysLeft: -10, priority: 'high', status: 'completed', description: 'Upload the newly received ISO 14001:2015 environmental management certification.', assignedTo: 'Self', relatedModule: 'Resources Center', details: ['Certificate scanned', 'Category updated', 'Stakeholders notified'], createdAt: 'Jan 03, 2025', updatedAt: 'Jan 15, 2025' },
  { id: 11, title: 'Supplier Payment Inquiry', type: 'Inquiry Response', category: 'inquiries', date: '2025-01-16', daysLeft: -9, priority: 'high', status: 'completed', description: 'Respond to Kansanshi Mining supplier inquiry regarding delayed payment.', assignedTo: 'Self', relatedModule: 'Inquiries', details: ['Payment status verified', 'Response sent', 'Follow-up scheduled'], createdAt: 'Jan 04, 2025', updatedAt: 'Jan 16, 2025' },
  { id: 12, title: 'Plant Supervisor Interview Scheduling', type: 'Job Posting', category: 'jobs', date: '2025-01-20', daysLeft: -5, priority: 'high', status: 'completed', description: 'Schedule interviews for 4 shortlisted Plant Supervisor candidates.', assignedTo: 'Self', relatedModule: 'Jobs Management', details: ['Interview panel confirmed', 'Conference room booked', 'Invitations sent'], createdAt: 'Jan 08, 2025', updatedAt: 'Jan 20, 2025' },
];

export const categoryModuleMap: Record<string, string> = {
  jobs: 'Jobs Management',
  resources: 'Resources Center',
  inquiries: 'Inquiries',
};

export const categoryTypeMap: Record<string, string[]> = {
  jobs: ['Job Posting', 'Interview Deadline', 'Hiring Deadline'],
  resources: ['Resource Upload', 'Resource Review', 'Document Update'],
  inquiries: ['Inquiry Response', 'Follow-up Deadline', 'Escalation Deadline'],
};
